### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by emlyn** [kivy/oscpy#29]
Looks like there's quite a lot new since 0.3.0, how about a new release?

**Comment by tshirtman** [comment]
Yep, seems like it would be a good idea :), hopefully this week end.

**Comment by tshirtman** [comment]
Done, thanks for the reminder, i'm quick to forget how much things are missing from previous releases.

https://github.com/kivy/oscpy/releases/tag/0.4.0
https://pypi.org/project/oscpy/
