### ISSUE TITLE
NameError: name 'OSCThreadServer' is not defined

### ISSUE THREAD

**Issue by patricksebastien** [kivy/oscpy#5]
Using your implementation on a raspberry pi 3 using pip install and python version 2.7.13, I have this error:

`osc = OSCThreadServer()
NameError: name 'OSCThreadServer' is not defined
`

The client is working just fine BTW.
Any idea?

**Comment by tshirtman** [comment]
Oh, indeed, i wrongly updated the example code, thanks for reporting.
