### ISSUE TITLE
No route to host results in crash

### ISSUE THREAD

**Issue by rasmuskreiner** [kivy/oscpy#57]
**Describe the bug**
oscpy chrashes when sent to a recipient not available on the network.

**To Reproduce**
Produced by sending a message to a recipient not available on the network.
**Logs/output**
   File "/usr/local/lib/python3.8/site-packages/oscpy/client.py", line 136, in send_message
     stats = send_message(
   File "/usr/local/lib/python3.8/site-packages/oscpy/client.py", line 68, in send_message
     sock.sendto(message, address)
 OSError: [Errno 65] No route to host

**Platform (please complete the following information):**
 - OS: MacOS 10.15.5
 - Python 3.8
 - oscpy 0.5

**Comment by tshirtman** [comment]
What do you think would be a more appropriate behavior?
